site_name: My Notes

theme:
  font:
    text: Roboto Slab
    code: JetBrains Mono
  name: material
  language: zh
  features:
    - navigation.path
    - navigation.top

site_url: https://sonata8.github.io/notes/

plugins:
  - tags