site_name: My Notes

theme:
  font:
    text: Roboto Slab
    code: JetBrains Mono
  name: material
  language: zh
  features:
    - navigation.path
    - navigation.top

site_url: https://sonata8.github.io/notes/

plugins:
  - tags

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # 如果你想使用 `$...$` 或 `$$...$$`
  
# extra_javascript:
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extra_css:
#   - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css

# extra_javascript:
#   - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
#   - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js

# extra_javascript:
#   - js/katex-init.js

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true  #代码块行号锚链接，默认false
      use_pygments: true  #在构建期间使用Pygments或在浏览器中使用 JavaScript 语法高亮器进行高亮显示，默认true
      auto_title: true  #自动为所有代码块添加标题，显示正在使用的语言的名称，默认false
      linenums: true #向所有代码块添加行号，默认false
      linenums_style: pymdownx-inline #三种添加行号的方法，建议table或pymdownx-inline。默认table
  - pymdownx.superfences