site_name: My Notes

theme:
  font:
    text: Roboto Slab
    code: JetBrains Mono
  name: material
  language: zh
  features:
    - navigation.path
    - navigation.top

site_url: https://sonata8.github.io/notes/

plugins:
  - tags

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # 如果你想使用 `$...$` 或 `$$...$$`
  
# extra_javascript:
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css